name: Job Poster

on:
  schedule:
    - cron: "0 * * * *"   # every hour (UTC)
  workflow_dispatch:      # lets you trigger it manually too

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Run job poster
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          REED_API_KEY: ${{ secrets.REED_API_KEY }}
        
        run: python poster.py
